<?php
/** Fresh-WordPress acceptance for structured M5 Research translations. */
wp_set_current_user(1);

function m5t_fail(string $message,mixed $context=null): never { fwrite(STDERR,"M5 TRANSLATIONS FAIL: {$message}\n"); if(null!==$context)fwrite(STDERR,wp_json_encode($context,JSON_PRETTY_PRINT)."\n"); exit(1); }
function m5t_request(string $method,string $route,string $token,array $body=array(),string $rid=''): WP_REST_Response { $r=new WP_REST_Request($method,'/research-manager/v1/'.ltrim($route,'/')); $r->set_header('Authorization','Bearer '.$token); $r->set_header('X-Research-Manager-Request-Id',''!==$rid?$rid:'req-'.wp_generate_uuid4()); $r->set_header('X-Research-Manager-Nonce','nonce-'.str_replace('-','',wp_generate_uuid4())); $r->set_header('X-Research-Manager-Timestamp',(string)time()); if($body){$r->set_header('Content-Type','application/json');$r->set_body((string)wp_json_encode($body));} return rest_do_request($r); }
function m5t_fixture(string $post_type,string $language): int { $id=wp_insert_post(array('post_type'=>$post_type,'post_status'=>'publish','post_title'=>'M5 '.str_replace('research_','',$post_type).' '.strtoupper($language),'post_name'=>'m5-'.sanitize_title($post_type).'-'.$language.'-'.substr(str_replace('-','',wp_generate_uuid4()),0,8),'post_excerpt'=>'Structured translation fixture.','post_content'=>'<p>Structured Research translation fixture.</p>'),true); if(is_wp_error($id))m5t_fail('fixture insert failed',$id->get_error_message()); update_post_meta((int)$id,'_research_language',$language); if('research_line'===$post_type){update_post_meta((int)$id,'_research_evidence_status','verified');update_post_meta((int)$id,'_research_status','active');} return (int)$id; }
function m5t_schema(int $post_id): string { $post=get_post($post_id); if(!$post instanceof WP_Post)return 'CreativeWork'; return match((string)$post->post_type){'research_dataset'=>'Dataset','research_software'=>'SoftwareSourceCode','research_line','research_project'=>'CreativeWork','research_output'=>function_exists('eduardo_research_output_schema_type')?(string)eduardo_research_output_schema_type($post_id):'ScholarlyArticle',default=>'CreativeWork'}; }
function m5t_fake_render(array $ids): void { add_filter('pre_http_request',static function($preempt,$args,$url)use($ids){foreach($ids as $id){$post=get_post((int)$id);if(!$post instanceof WP_Post)continue;$permalink=(string)get_permalink((int)$id);if(untrailingslashit((string)$url)!==untrailingslashit($permalink))continue;$lang=function_exists('eduardo_research_post_language')?eduardo_research_post_language((int)$id):(string)get_post_meta((int)$id,'_research_language',true);$safe=esc_url($permalink);$schema=esc_html(m5t_schema((int)$id));$title=esc_html((string)$post->post_title);$body='<!doctype html><html lang="'.esc_attr($lang).'"><head><link rel="canonical" href="'.$safe.'"><link rel="alternate" hreflang="'.esc_attr($lang).'" href="'.$safe.'"><meta property="og:url" content="'.$safe.'"><script type="application/ld+json">{"@context":"https://schema.org","@type":"'.$schema.'"}</script></head><body><article><h1>'.$title.'</h1></article></body></html>';return array('headers'=>array(),'body'=>$body,'response'=>array('code'=>200,'message'=>'OK'),'cookies'=>array(),'filename'=>null);}return $preempt;},10,3); }
function m5t_plan(string $token,string $operation,array $payload,string $rid=''): array { $r=m5t_request('POST','research-translations/plan',$token,array('operation'=>$operation,'payload'=>$payload),$rid); if(200!==$r->get_status())m5t_fail('translation plan failed: '.$operation,$r->get_data()); return (array)($r->get_data()['data']??array()); }
function m5t_apply(string $token,string $plan_id): array { $r=m5t_request('POST','research-translations/plans/'.rawurlencode($plan_id).'/apply',$token,array('confirm'=>true)); if(200!==$r->get_status())m5t_fail('translation Apply failed',$r->get_data()); $d=(array)($r->get_data()['data']??array()); if(empty($d['operation_id'])||empty($d['result']['verified']))m5t_fail('translation Apply result invalid',$d); return $d; }
function m5t_verify(string $token,string $op): array { $r=m5t_request('POST','research-translations/operations/'.rawurlencode($op).'/verify',$token,array('rendered'=>true)); if(200!==$r->get_status())m5t_fail('translation Verify request failed',$r->get_data()); $d=(array)($r->get_data()['data']??array()); if(empty($d['stored_verification']['verified'])||empty($d['rendered_verification']['verified']))m5t_fail('translation Verify failed',$d); return $d; }
function m5t_rollback(string $token,string $op): array { $r=m5t_request('POST','research-translations/operations/'.rawurlencode($op).'/rollback',$token,array('confirm'=>true)); if(200!==$r->get_status())m5t_fail('translation Rollback failed',$r->get_data()); $d=(array)($r->get_data()['data']??array()); if('rolled-back'!==(string)($d['status']??'')||empty($d['rollback_restored_baseline']))m5t_fail('translation Rollback baseline invalid',$d); return $d; }

$blueprint=Eduardo_Research_Manager::blueprint_store()->canonical(); if(is_wp_error($blueprint))m5t_fail('blueprint unavailable'); $seed=Eduardo_Research_Manager::pipeline()->apply($blueprint); if(is_wp_error($seed)||empty($seed['verified']))m5t_fail('seed failed',$seed); rest_get_server();

// translations.write must be independently granted.
$ro=Eduardo_Research_Manager::remote_credentials()->issue_token(array('site.read','site.diagnostics','translations.read','operations.apply','operations.rollback'),1,'CI M5 translation read-only'); if(is_wp_error($ro)||empty($ro['token']))m5t_fail('read-only token failed'); $ro_token=(string)$ro['token'];
$line_a=m5t_fixture('research_line','en'); $line_b=m5t_fixture('research_line','es');
$denied=m5t_request('POST','research-translations/plan',$ro_token,array('operation'=>'translation-pair','payload'=>array('first_id'=>$line_a,'second_id'=>$line_b,'evidence_confirmed'=>true,'evidence_reference'=>'ci:denied'))); if(403!==$denied->get_status()||'scope_denied'!==(string)($denied->get_data()['code']??''))m5t_fail('translations.write scope not enforced',$denied->get_data());

$issued=Eduardo_Research_Manager::remote_credentials()->issue_token(array('site.read','site.diagnostics','translations.read','translations.write','operations.apply','operations.rollback'),1,'CI M5 translations'); if(is_wp_error($issued)||empty($issued['token']))m5t_fail('token issuance failed'); $token=(string)$issued['token'];
$cap=m5t_request('GET','capabilities',$token); $control=(array)($cap->get_data()['data']['research_translation_control']??array()); if(200!==$cap->get_status()||'M5'!==(string)($control['milestone']??'')||empty($control['available'])||!in_array('research_dataset',(array)($control['post_types']??array()),true)||empty($control['pair_requirements']['published_only'])||empty($control['insights_use_dedicated_m4_gateway']))m5t_fail('translation capabilities incomplete',$cap->get_data());

// A normal WordPress post must never enter the structured M5 translation surface.
$post_id=wp_insert_post(array('post_type'=>'post','post_status'=>'publish','post_title'=>'Arbitrary post'),true); update_post_meta((int)$post_id,'_research_language','en');
$blocked=m5t_request('POST','research-translations/plan',$token,array('operation'=>'translation-pair','payload'=>array('first_id'=>$post_id,'second_id'=>$line_b,'evidence_confirmed'=>true,'evidence_reference'=>'ci:blocked'))); if(400!==$blocked->get_status())m5t_fail('generic post entered structured translation surface',$blocked->get_data());

$pairs=array('research_line'=>array($line_a,$line_b));
foreach(array('research_output','research_project','research_software','research_dataset') as $type){$pairs[$type]=array(m5t_fixture($type,'en'),m5t_fixture($type,'es'));}
$operations=array();
foreach($pairs as $type=>$ids){[$en,$es]=$ids;$reference='ci:m5-translation:'.$type;$rid='req-m5t-'.substr(str_replace('-','',wp_generate_uuid4()),0,20);$payload=array('first_id'=>$en,'second_id'=>$es,'evidence_confirmed'=>true,'evidence_reference'=>$reference);$plan=m5t_plan($token,'translation-pair',$payload,$rid);if(empty($plan['apply_allowed']))m5t_fail('pair plan blocked for '.$type,$plan);if((int)get_post_meta($en,'_research_translation_es',true)!==0)m5t_fail('Preview mutated EN relation for '.$type);
$replay=m5t_request('POST','research-translations/plan',$token,array('operation'=>'translation-pair','payload'=>$payload),$rid);if(200!==$replay->get_status()||empty($replay->get_data()['idempotent_replay'])||(string)($replay->get_data()['data']['plan_id']??'')!==(string)$plan['plan_id'])m5t_fail('idempotent pair plan failed for '.$type,$replay->get_data());
$applied=m5t_apply($token,(string)$plan['plan_id']);$op=(string)$applied['operation_id'];if((int)get_post_meta($en,'_research_translation_es',true)!==$es||(int)get_post_meta($es,'_research_translation_en',true)!==$en)m5t_fail('bilateral pair missing for '.$type);if($reference!==(string)get_post_meta($en,'_eduardo_research_translation_evidence',true)||$reference!==(string)get_post_meta($es,'_eduardo_research_translation_evidence',true))m5t_fail('pair evidence reference missing for '.$type);
m5t_fake_render(array($en,$es));m5t_verify($token,$op);remove_all_filters('pre_http_request');
$candidates=m5t_request('GET','research-translations',$token); // Route exists; required query is tested through editor below because WP_REST_Request route strings do not parse query strings.
$list=Eduardo_Research_Manager::translation_editor()->list_candidates($type,'en');if(is_wp_error($list))m5t_fail('candidate listing failed for '.$type,$list->get_error_message());$found=false;foreach($list as $row){if((int)($row['post_id']??0)===$en)$found=true;}if(!$found)m5t_fail('paired EN candidate not discoverable for '.$type,$list);
$inspect=m5t_request('GET','research-translations/'.$en,$token);if(200!==$inspect->get_status()||(int)($inspect->get_data()['data']['counterpart_id']??0)!==$es)m5t_fail('translation inspect failed for '.$type,$inspect->get_data());
$operations[$type]=array('pair_operation'=>$op,'en'=>$en,'es'=>$es,'reference'=>$reference);}

// Stale Preview: modify one target after unpair Preview.
$dataset=$operations['research_dataset'];$unpair_plan=m5t_plan($token,'translation-unpair',array('post_id'=>$dataset['en'],'evidence_confirmed'=>true,'evidence_reference'=>'ci:m5-unpair-stale'));wp_update_post(array('ID'=>$dataset['en'],'post_excerpt'=>'External edit after translation Preview'));$stale=m5t_request('POST','research-translations/plans/'.rawurlencode((string)$unpair_plan['plan_id']).'/apply',$token,array('confirm'=>true));$code=(string)($stale->get_data()['code']??'');if(409!==$stale->get_status()||!in_array($code,array('stale_revision','research_manager_translation_editor_stale_preview'),true))m5t_fail('stale translation Preview was not rejected',$stale->get_data());wp_update_post(array('ID'=>$dataset['en'],'post_excerpt'=>'Structured translation fixture.'));

// Unpair one pair, verify, then rollback it to paired state.
$project=$operations['research_project'];$up=m5t_plan($token,'translation-unpair',array('post_id'=>$project['en'],'evidence_confirmed'=>true,'evidence_reference'=>'ci:m5-unpair-project'));$uo=m5t_apply($token,(string)$up['plan_id']);m5t_fake_render(array($project['en'],$project['es']));m5t_verify($token,(string)$uo['operation_id']);remove_all_filters('pre_http_request');if((int)get_post_meta($project['en'],'_research_translation_es',true)!==0||(int)get_post_meta($project['es'],'_research_translation_en',true)!==0)m5t_fail('project unpair failed');m5t_rollback($token,(string)$uo['operation_id']);$restored=Eduardo_Research_Manager::translations()->verify_pair($project['en'],$project['es']);if(is_wp_error($restored)||empty($restored['verified']))m5t_fail('unpair rollback did not restore pair',$restored);

// Roll back every original pair to the unpaired baseline.
foreach(array_reverse($operations,true) as $type=>$state){m5t_rollback($token,(string)$state['pair_operation']);$a=Eduardo_Research_Manager::translations()->verify_unpaired((int)$state['en']);$b=Eduardo_Research_Manager::translations()->verify_unpaired((int)$state['es']);if(is_wp_error($a)||is_wp_error($b)||empty($a['verified'])||empty($b['verified']))m5t_fail('pair rollback did not restore baseline for '.$type);}
foreach($pairs as $ids){foreach($ids as $id)wp_delete_post((int)$id,true);}wp_delete_post((int)$post_id,true);
fwrite(STDOUT,"M5 structured Research translations OK\n");
